# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: true
